![imagen](./img/espectadores.jpg)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
import numpy as np

In [28]:
my_array = np.arange(10)
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [29]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [4]:
my_matrix = np.arange(20).reshape((4,5))
my_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
my_matrix.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [10]:
my_array5 = my_matrix[[0][1:3][1][:2]]

IndexError: list index out of range

In [8]:
print(my_array5)

[]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [5]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [10]:
x8 = np.where(x == "Loro", "Loro")
print(x8)

ValueError: either both or neither of x and y should be given

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [15]:
array_9 = np.random.rand(20).reshape(5,4)
print(array_9)

[[0.73512387 0.06776033 0.10499957 0.01483899]
 [0.34859514 0.12260346 0.93329173 0.05625727]
 [0.60897265 0.83017904 0.39705412 0.56378276]
 [0.87066867 0.53631923 0.43799363 0.3688347 ]
 [0.14934955 0.79720017 0.37433469 0.53226039]]


In [16]:
left, right = np.hsplit(array_9, [2])
print(left)
print(right)

[[0.73512387 0.06776033]
 [0.34859514 0.12260346]
 [0.60897265 0.83017904]
 [0.87066867 0.53631923]
 [0.14934955 0.79720017]]
[[0.10499957 0.01483899]
 [0.93329173 0.05625727]
 [0.39705412 0.56378276]
 [0.43799363 0.3688347 ]
 [0.37433469 0.53226039]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [24]:
array_11 = np.full((10), 0)
print(array_11)
print(array_11.nbytes)

[0 0 0 0 0 0 0 0 0 0]
80


In [25]:
array_11[3]=1
print(array_11)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [34]:
my_array12 = np.arange(10,50)
my_array12[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [40]:
my_array13 = np.array([1,2,0,0,4,0])
np.argwhere(my_array13 !=0)

array([[0],
       [1],
       [4]])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
array_14 = np.random.rand(100).reshape(10,10)
print(array_14)
print(array_14.max())
print(array_14.min())

[[0.5367691  0.17507896 0.55098952 0.13016583 0.78198762 0.07203656
  0.97835921 0.52019189 0.52682952 0.76592857]
 [0.86699344 0.19089847 0.90018432 0.72819156 0.8805922  0.0212953
  0.26022361 0.71145472 0.11199497 0.29246526]
 [0.26551582 0.22805011 0.871972   0.95802122 0.75686656 0.52504476
  0.78323324 0.82528473 0.74382041 0.27020151]
 [0.53613679 0.82660215 0.42540351 0.34326163 0.32554925 0.63109886
  0.56023626 0.56729174 0.87204011 0.54517391]
 [0.12534226 0.94283359 0.76726329 0.81695108 0.46775325 0.97671378
  0.18205715 0.24158701 0.10166604 0.08126646]
 [0.61515386 0.65549691 0.97071975 0.76674534 0.48361966 0.6771364
  0.35863611 0.53603609 0.09543545 0.73885768]
 [0.41869853 0.64878635 0.17503372 0.47402945 0.15226724 0.36988502
  0.83247739 0.69210749 0.89015357 0.29647427]
 [0.21516286 0.26595579 0.01014649 0.77959294 0.28508845 0.65204688
  0.63398672 0.89605702 0.53950347 0.94299154]
 [0.92344786 0.05247461 0.93925632 0.81494855 0.73150614 0.75943201
  0.45488133 0

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [21]:
array_15 = np.random.rand(30)
print(array_15)
print(np.median(array_15))

[0.75026408 0.17693841 0.71671067 0.07611073 0.35254532 0.95481795
 0.89344792 0.32054734 0.22169682 0.85463764 0.24008896 0.21629232
 0.59679576 0.27322245 0.57778989 0.00386428 0.94606343 0.12423377
 0.34336813 0.57614964 0.86664404 0.2882287  0.45444447 0.50301403
 0.43949771 0.53180159 0.17015318 0.77089778 0.46431466 0.2058922 ]
0.4469710902132343


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [37]:
my_array16 = np.random.rand(16).reshape((4,4))
my_array16

array([[0.35302549, 0.77675164, 0.84281938, 0.74485578],
       [0.92593562, 0.88818628, 0.50510368, 0.13942482],
       [0.51422569, 0.12667301, 0.10606116, 0.66620957],
       [0.76247672, 0.3093843 , 0.94548358, 0.34612861]])

In [38]:
my_array16 = np.ones((10,10))

my_array16[1:-1,1:-1] = 0
my_array16

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [14]:
my_array18 = np.array([[0, 1], [1, 0]])
np.tile(my_array18, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.