![imagen](./img/espectadores.jpg)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [31]:
import numpy as np

In [28]:
my_array = np.arange(10)
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [29]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [42]:
my_matrix = np.arange(1,21).reshape((4,5))
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
my_matrix.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [56]:
my_matrix[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [50]:
my_array5 = my_matrix[:2,:2]

In [51]:
print(my_array5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [54]:
my_array6 = my_matrix[::2, ::2]

In [55]:
print(my_array6)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [69]:
my_array7 = my_matrix[:3:,::-1]

In [70]:
print(my_array7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [80]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [101]:
x8 = np.where(x != "Loro", None,x)
print(x8)

['Loro' None None 'Loro' None]


In [97]:
lista = [a for a in x if a=="Loro"]
lista


['Loro', 'Loro']

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [15]:
array_9 = np.random.rand(20).reshape(5,4)
print(array_9)

[[0.73512387 0.06776033 0.10499957 0.01483899]
 [0.34859514 0.12260346 0.93329173 0.05625727]
 [0.60897265 0.83017904 0.39705412 0.56378276]
 [0.87066867 0.53631923 0.43799363 0.3688347 ]
 [0.14934955 0.79720017 0.37433469 0.53226039]]


In [16]:
left, right = np.hsplit(array_9, [2])
print(left)
print(right)

[[0.73512387 0.06776033]
 [0.34859514 0.12260346]
 [0.60897265 0.83017904]
 [0.87066867 0.53631923]
 [0.14934955 0.79720017]]
[[0.10499957 0.01483899]
 [0.93329173 0.05625727]
 [0.39705412 0.56378276]
 [0.43799363 0.3688347 ]
 [0.37433469 0.53226039]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [72]:
my_array10 = my_matrix[::-1,::-1]

In [73]:
print(my_array10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [24]:
array_11 = np.full((10), 0)
print(array_11)
print(array_11.nbytes)

[0 0 0 0 0 0 0 0 0 0]
80


In [25]:
array_11[3]=1
print(array_11)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [34]:
my_array12 = np.arange(10,50)
my_array12[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [40]:
my_array13 = np.array([1,2,0,0,4,0])
np.argwhere(my_array13 !=0)

array([[0],
       [1],
       [4]])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [7]:
array_14 = np.random.rand(100).reshape(10,10)
print(array_14)
print("*"*20)
print(array_14.max())
print("*"*20)
print(array_14.min())

[[0.94830473 0.8952979  0.793678   0.5501819  0.34333379 0.08360184
  0.31398483 0.57079034 0.37079371 0.63147282]
 [0.38991396 0.79416531 0.25561472 0.32988982 0.49778218 0.30096912
  0.25705514 0.06111813 0.61208288 0.45900856]
 [0.98174614 0.1098691  0.38062142 0.59557773 0.63030336 0.42937301
  0.81703908 0.77097873 0.11171576 0.3188399 ]
 [0.68407656 0.90219135 0.77253482 0.42674289 0.89566572 0.6391441
  0.17505222 0.61654793 0.48062825 0.81283878]
 [0.68623115 0.4002271  0.71004137 0.76550539 0.91881019 0.85635377
  0.3743178  0.82017056 0.8360229  0.63499991]
 [0.24333545 0.61592759 0.48664179 0.87185756 0.50658916 0.15700021
  0.39606878 0.99308714 0.19767937 0.0654767 ]
 [0.54255081 0.57967938 0.43319447 0.508821   0.57345803 0.94255525
  0.17518833 0.56892006 0.62696414 0.00559056]
 [0.79926475 0.15151498 0.02346041 0.55677162 0.65320201 0.26391193
  0.82846799 0.19088692 0.52746896 0.38222842]
 [0.23441819 0.87936266 0.81213696 0.64977564 0.95524141 0.77015402
  0.75433417 

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [21]:
array_15 = np.random.rand(30)
print(array_15)
print(np.median(array_15))

[0.75026408 0.17693841 0.71671067 0.07611073 0.35254532 0.95481795
 0.89344792 0.32054734 0.22169682 0.85463764 0.24008896 0.21629232
 0.59679576 0.27322245 0.57778989 0.00386428 0.94606343 0.12423377
 0.34336813 0.57614964 0.86664404 0.2882287  0.45444447 0.50301403
 0.43949771 0.53180159 0.17015318 0.77089778 0.46431466 0.2058922 ]
0.4469710902132343


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [37]:
my_array16 = np.random.rand(16).reshape((4,4))
my_array16

array([[0.35302549, 0.77675164, 0.84281938, 0.74485578],
       [0.92593562, 0.88818628, 0.50510368, 0.13942482],
       [0.51422569, 0.12667301, 0.10606116, 0.66620957],
       [0.76247672, 0.3093843 , 0.94548358, 0.34612861]])

In [38]:
my_array16 = np.ones((10,10))

my_array16[1:-1,1:-1] = 0
my_array16

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [86]:
my_array17 = np.zeros((8, 8), dtype=int)
my_array17[1::2, ::2] = 1  
my_array17[::2, 1::2] = 1 

In [87]:
my_array17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [14]:
my_array18 = np.array([[0, 1], [1, 0]])
np.tile(my_array18, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [92]:
matrix19 = np.random.randint(25, size = (5,5))
matrix19

array([[13, 15, 15, 13, 20],
       [19,  3, 19, 17,  7],
       [ 2, 14, 21,  5,  2],
       [ 6,  7,  2,  2,  5],
       [11, 19,  4, 19, 14]])

In [95]:
media = np.mean(matrix19)
dst = np.std(matrix19)

matrix19 = (matrix19 - media) / dst

In [96]:
matrix19

array([[ 0.30796742,  0.60989626,  0.60989626,  0.30796742,  1.36471837],
       [ 1.21375395, -1.2016768 ,  1.21375395,  0.91182511, -0.59781911],
       [-1.35264122,  0.45893184,  1.5156828 , -0.89974796, -1.35264122],
       [-0.74878353, -0.59781911, -1.35264122, -1.35264122, -0.89974796],
       [ 0.00603858,  1.21375395, -1.05071238,  1.21375395,  0.45893184]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [12]:
my_array20 = np.arange(11)

my_array20_2 = np.where((my_array20 >=3) & (my_array20 <= 8), -1, my_array20) 
print(my_array20_2)


[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [13]:
my_array20_3 = np.where((my_array20 >=3) & (my_array20 <= 8), -(my_array20), my_array20) 
print(my_array20_3)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [34]:
tablero = np.array(""*100)
tablero.reshape((10,10))

ValueError: cannot reshape array of size 1 into shape (10,10)